### ISSUE TITLE
Background image doesnt seem to work

### ISSUE THREAD

**Issue by EnteSuesssauer15** [Saltssaumure/w9x-discord-theme#19]
added 
`url(link);`
and nothing changes, just the same one color background

**Comment by EnteSuesssauer15** [comment]
update, the complete theme is broken since today 
![image](https://github.com/Saltssaumure/w9x-discord-theme/assets/87829672/51064f89-f943-4356-b0d5-531afc49119c)

**Comment by matt1432** [comment]
Can confirm this theme does not work as of the latest update

**Comment by Saltssaumure** [comment]
Fixed.

**Comment by EnteSuesssauer15** [comment]
no its not i still cant set a  background image 
`url(http://drecksladen.ddnss.de:7745/windowsxp.jpg);`
![image](https://github.com/Saltssaumure/w9x-discord-theme/assets/87829672/c8e1dbe5-894c-4cdb-8a3f-bfac2ba15c8c)

**Comment by Saltssaumure** [comment]
Your issue is caused by Discord being unable to access that address, not by the theme.

**Comment by EnteSuesssauer15** [comment]
when i type the address in my browser i clearly see a picture, what am i doing wrong?

**Comment by Saltssaumure** [comment]
That site does not support HTTPS so Discord won't load the image. Rehost the image somewhere else (eg. imgur.com), or since you're looking for the XP background image, I already have that hosted on Github: https://saltssaumure.github.io/xp-discord-theme/img/bliss.avif

**Comment by Saltssaumure** [comment]
Just to document that this is the reason:
![image](https://github.com/Saltssaumure/w9x-discord-theme/assets/29710355/40869837-aacd-4a12-a3b5-9a78f73d153c)
https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
